[PYPSUCURVETRACE]
SAY_HELLO       = FALSE
ASK_DUT_CFG     = FALSE

[PSU1]
TYPE            = XINYI
MODEL           = XY-6020L
COMPORT         = COM4
MODBUS_ADDR     = 1
NUMSTABLEREAD   = 1

[PSU2]
TYPE            = XINYI
MODEL           = XY-6020L
COMPORT         = COM4
MODBUS_ADDR     = 2
NUMSTABLEREAD   = 1

[HEATERBLOCK_disabled]

[GLOSSARY]
;   [PYPSUCURVETRACE]
;   SAY_HELLO              = boolean, Whether to print the hello message (also disabled by --no-hello cmdline argument)
;   ASK_DUT_CFG            = boolean, Whether to ask for a DUT config path or entry when --config is not specified, ctrace.py / curvetrace (!! EXP)
;   CURVETRACE_ROOT        = specify root directory of pypsucurvetrace cloned repo. Defaults to parent directory of env:VIRTUAL_ENV (!! EXP)
;   CURVETRACE_CFG         = alternatively, specify an external location to scan for a CFG file. If found, overrides default CFG file. (!! EXP)
;
;   [PSUx]
;   TYPE                   = REQUIRED, string, [ 'KORAD' , 'VOLTCRAFT' , 'BK' , 'RIDEN' , 'SALUKI' , 'XINYI']
;   MODEL                  = string, Just there for your own info, for now... (!! EXP)
;   COMPORT                = REQUIRED, string, What serial port to use. Windows (COMx) & Unix (/dev/tty) formats supported.
;   MODBUS_ADDR            = integer, Enables ModBus multi-tenancy (usually on same comport) (!! EXP)
;   NUMSTABLEREADINGS      = integer, Number of consistent samples withing X range required for reading validation (X = Unknown for now)
;       [CALIBRATION] (!! EXP) NOT IMPLEMENTED, USE ROOT OF [PSUx] INSTEAD.
;       V_SET_CALPOLY      = tuple(float, float), Polynomial tuple of two floats that define the voltage setting calibration
;       V_READ_CALPOLY     = tuple(float, float), Polynomial tuple of two floats that define the voltage reading calibration
;       I_SET_CALPOLY      = tuple(float, float), Polynomial tuple of two floats that define the current setting calibration
;       I_READ_CALPOLY     = tuple(float, float), Polynomial tuple of two floats that define the current reading calibration
;
;   [HEATERBLOCK]
;   Gets very hot
;   Don't touch
;   Very ouchie